spring.application.name=auth-service

server.port=${PORT:8082}

# Eureka
eureka.client.service-url.defaultZone=http://${EUREKA_SERVER_URL:localhost:8761}/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# User Service - Use Eureka service discovery (load-balanced RestClient)
user-service.url=${USER_SERVICE_URL:http://user-service}

# Actuator
management.endpoints.web.exposure.include=health,info